version: '3'
services:
  app:
    build: .
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234567
      - POSTGRES_DB=card-transaction
  db:
    image: postgres
    volumes:
      - db_data:/var/lib/postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234567
      - POSTGRES_DB=card-transaction
    ports:
      - "5432:5432"
volumes:
  db_data: